using System.IO.Compression;
using Xunit;

namespace Quarp.CartKit.Tests;

/// <summary>
/// <c>quarp new</c> drops a dev-only <c>.quarp/cart.csproj</c> into the cartridge folder so an
/// IDE can show the QRP1001-QRP1003 diagnostics while the author types (M2 work order).
/// That folder must be invisible to the cartridge itself, and "invisible" has four separate
/// meanings that can each break on their own — so each is pinned here.
///
/// <para>The failure this guards against is not theoretical: an IDE that builds the project
/// fills <c>.quarp/obj/</c> with generated <c>.cs</c> files, and a loader that globbed
/// <c>**/*.cs</c> would compile <c>AssemblyInfo.cs</c> into the cartridge, blow the 64 KB code
/// budget, and hot-reload in a loop as the IDE rebuilt.</para>
/// </summary>
public class DevProjectIsolationTests : IDisposable
{
    private readonly string _folder;

    public DevProjectIsolationTests()
    {
        _folder = Path.Combine(Path.GetTempPath(), "quarp-devproj-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(_folder, "src"));
        Directory.CreateDirectory(Path.Combine(_folder, ".quarp", "obj", "Debug", "net10.0"));

        File.WriteAllText(Path.Combine(_folder, "manifest.json"),
            "{\"name\":\"devproj\",\"author\":\"\",\"profile\":8}");
        File.WriteAllText(Path.Combine(_folder, "src", "main.cs"), """
            using Quarp.Api;

            public sealed class DevProjCart : Cartridge
            {
                public override void Draw() => Cls(0);
            }
            """);
        File.WriteAllText(Path.Combine(_folder, ".quarp", "cart.csproj"), "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        // What an IDE build leaves behind, including a second Cartridge subclass that would
        // make CartHost refuse to load the cart if it ever reached the compilation.
        File.WriteAllText(
            Path.Combine(_folder, ".quarp", "obj", "Debug", "net10.0", "cart.AssemblyInfo.cs"),
            "// <auto-generated/>\npublic sealed class GeneratedIntruder : Quarp.Api.Cartridge { }\n");
    }

    public void Dispose() => Directory.Delete(_folder, recursive: true);

    [Fact]
    public void LoaderSeesOnlyTheCartridgeSources()
    {
        CartData data = CartSource.LoadFolder(_folder);

        CartSourceFile only = Assert.Single(data.Sources);
        Assert.Equal("src/main.cs", only.RelativePath);
    }

    [Fact]
    public void PackerLeavesTheDevFolderOut()
    {
        string package = _folder + ".quarp8";
        try
        {
            Quarp8Package.Pack(_folder, package);

            using ZipArchive zip = ZipFile.OpenRead(package);
            var names = new List<string>();
            foreach (ZipArchiveEntry entry in zip.Entries)
            {
                names.Add(entry.FullName.Replace('\\', '/'));
            }
            Assert.DoesNotContain(names, n => n.StartsWith(".quarp", StringComparison.Ordinal));
            Assert.Contains("manifest.json", names);
            Assert.Contains("src/main.cs", names);
        }
        finally
        {
            File.Delete(package);
        }
    }

    /// <summary>
    /// A folder cart and its package must still hash the same with the dev project present —
    /// otherwise packing a cart would invalidate every replay recorded against the folder.
    /// </summary>
    [Fact]
    public void DevFolderDoesNotAffectTheCartIdentity()
    {
        byte[] withDevProject = CartIdentity.Compute(CartSource.LoadFolder(_folder));

        Directory.Delete(Path.Combine(_folder, ".quarp"), recursive: true);
        byte[] without = CartIdentity.Compute(CartSource.LoadFolder(_folder));

        Assert.Equal(without, withDevProject);
    }

    /// <summary>
    /// The watcher must not treat an IDE's background build as an author's edit — otherwise
    /// opening the folder in Rider triggers a hot-reload storm.
    /// </summary>
    [Fact]
    public void WatcherIgnoresTheDevFolder()
    {
        using var watcher = new CartWatcher(_folder);
        // Drain anything the constructor may have latched onto before the window opened.
        Thread.Sleep(CartWatcher.DebounceMilliseconds * 2);
        watcher.ConsumeReloadRequest();

        File.WriteAllText(
            Path.Combine(_folder, ".quarp", "obj", "Debug", "net10.0", "cart.AssemblyInfo.cs"),
            "// touched by a background build\n");
        Thread.Sleep(CartWatcher.DebounceMilliseconds * 3);

        Assert.False(watcher.ConsumeReloadRequest());
    }
}
